apiVersion: dashboard.opendatahub.io/v1
kind: AcceleratorProfile
metadata:
  name: huge-gpu-card
  namespace: redhat-ods-applications
spec:
  displayName: Huge GPU Card (H100)
  enabled: false
  identifier: nvidia.com/gpu
  tolerations:
    - effect: NoSchedule
      key: nvidia.com/gpu
      value: NVIDIA-H100-SHARED
