apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - accprof-t4.yaml
  - accprof-a10.yaml
  - accprof-a100.yaml
  - accprof-h100.yaml

patchesStrategicMerge:
  - disable-gpu-default.yaml
